version: "3.8"
services:
  app:
    build:
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    environment:
      CB_URL: couchbase://couchbase-server
      CB_USERNAME: admin
      CB_PASSWORD: Password
      CB_BUCKET: todoapp
    depends_on:
      couchbase-server:
        condition: service_healthy
    restart: always
  couchbase-server:
    build: ./couchbase-server
    ports:
     - 8091-8096:8091-8096
     - 11210:11210
    environment:  
      - CLUSTER_NAME=couchbase-demo
      - COUCHBASE_ADMINISTRATOR_USERNAME=Administrator
      - COUCHBASE_ADMINISTRATOR_PASSWORD=Password
      - COUCHBASE_BUCKET=todoapp
      - COUCHBASE_BUCKET_RAMSIZE=512
      - COUCHBASE_RBAC_USERNAME=admin
      - COUCHBASE_RBAC_PASSWORD=Password
      - COUCHBASE_RBAC_NAME=admin
      - COUCHBASE_RAM_SIZE=2048
      - COUCHBASE_INDEX_RAM_SIZE=512
    working_dir: /opt/couchbase
    stdin_open: true
    tty: true      
    entrypoint: [""]
    command: sh -c "/opt/couchbase/init/init-cbserver.sh"
    healthcheck:
      test: ["CMD", "curl", "-IL", "http://localhost:8091"]
      interval: 10s
      retries: 10
      start_period: 20s
      timeout: 10s
